export const GET_DECKS = 'GET_DECKS';
export const MOBILE_FLASH_CARDS_KEY = 'MOBILE_FLASH_CARDS_KEY_RICARDO';
export const NEW_DECK = 'NEW_DECK';
export const NEW_QUESTION = 'NEW_QUESTION';
export const NOTIFICATION_KEY = 'NOTIFICATION_KEY_FLASH_CARDS_KEY_RICARDO';
